cz_admin_page:
    resource: "@CzAdminBundle/Controller/PageController.php"
    type:     annotation

cz_i18_lang:
    resource: "@CzI18Bundle/Controller/LangController.php"
    type:     annotation

cz_i18_pages:
    resource: "@CzI18Bundle/Controller/PagesController.php"
    type:     annotation

cz_i18:
    resource: "@CzI18Bundle/Resources/config/routing.yml"
    prefix:   /

cz_manager:
    resource: "@CzManagerBundle/Resources/config/routing.yml"
    prefix:   /

cz_admin:
    resource: "@CzAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

oneup_uploader:
    resource: .
    type: uploader

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

admin_chmabre:
    resource: .
    type: extra
#
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#    prefix:   /admin