<?php

namespace Cz\AdminBundle\Repository;

/**
 * CarrouselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarrouselRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLang($lang)
    {
        $qb = $this
            ->createQueryBuilder('s')
//            ->leftJoin('s.image', 'o')
//            ->addSelect('o')
            ->leftJoin('s.namecs', 'p')
            ->addSelect('p')
            ->where('p.lang = :lang')
            ->setParameter('lang', $lang)
            ->orderBy('s.id', 'DESC')
            ;

        return  $qb
            ->getQuery()
            ->getResult();
      }

}
