<?php

namespace Cz\AdminBundle\Repository;

/**
 * PersonnalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnalisationRepository extends \Doctrine\ORM\EntityRepository
{
}
